lint:
  files_unchanged:
    - .github/workflows/linting.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/ISSUE_TEMPLATE/feature_request.yml
nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: Sarath Murugan
  description: This Pipeline analyses the targeted panel sequencing data from liquid
    biopsy samples with more accuracy
  force: false
  is_nfcore: true
  name: autoseq
  org: nf-core
  outdir: .
  version: 1.0.0dev
